# Generated by Django 4.2.1 on 2024-02-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='team',
            new_name='team_of_employee',
        ),
    ]
